main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('logout', views.logoutUser, name='logoutUser'),
]

portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('prof/', include('prof.urls')),
    path('student/', include('student.urls')),
]

student/api/urls.py
from student.views.exams import exams
from django.urls import path, include
from . import results, exams

urlpatterns = [
    path('results/<int:pk>', results.Results.as_view()),
    path('exams/<int:pk>', exams.Exam.as_view()),
]

student/urls.py
from django.urls import path, include
from . import views

app_name = 'student'

urlpatterns = [
                                # HOME
    path('', views.index, name='index'),
    
                                # EXAM
    path('exams', views.exams, name='exams'),
    path('results', views.results, name='results'),

    path('api/', include('student.api.urls')),
]

student/models.py
from django.db import models
from main.models import *
from django.contrib.auth.models import User

# Create your models here.
class Stu_Question(Question_DB):
    professor = None
    student = models.ForeignKey(User, limit_choices_to={'groups__name': "Student"}, on_delete=models.CASCADE, null=True)
    choice = models.CharField(max_length=3, default="E")


class StuExam_DB(models.Model):
    student = models.ForeignKey(User, limit_choices_to={'groups__name': "Student"}, on_delete=models.CASCADE, null=True)
    examname = models.CharField(max_length=100)
    qpaper = models.ForeignKey(Question_Paper, on_delete=models.CASCADE, null=True)
    questions = models.ManyToManyField(Stu_Question)
    score = models.IntegerField(default=0)
    completed = models.IntegerField(default=0)


class StuResults_DB(models.Model):
    student = models.ForeignKey(User, limit_choices_to={'groups__name': "Student"}, on_delete=models.CASCADE, null=True)
    exams = models.ManyToManyField(StuExam_DB)

prof/views/student.py
from django.shortcuts import render
from main.models import *
from django.contrib.auth.models import User
from django.http import HttpResponseForbidden


def view_students(request):
    prof = request.user
    return render(request, 'prof/student/view_students.html', {
        'students': User.objects.filter(groups__name='Student'), 'prof': prof
    })
    

student/views/exams.py
from django.shortcuts import render, redirect
from django.http import HttpResponseForbidden
from main.models import *
from django.contrib.auth.models import User
from student.models import *
from django.utils import timezone


def exams(request):
    student = request.user

    studentGroup = Special_Students.objects.filter(students=student)
    studentExamsList = StuExam_DB.objects.filter(student=student)

    if request.method == 'POST' and not request.POST.get('papertitle', False):
        paper = request.POST['paper']
        stuExam = StuExam_DB.objects.get(examname=paper, student=student)
        qPaper = stuExam.qpaper
        examMain = Exam_Model.objects.get(name=paper)

        # TIME COMPARISON
        exam_start_time = examMain.start_time
        curr_time = timezone.now()

        if curr_time < exam_start_time:
            return redirect('student:exams')

        stuExam.questions.all().delete()

        qPaperQuestionsList = qPaper.questions.all()
        for ques in qPaperQuestionsList:
            student_question = Stu_Question(question=ques.question, optionA=ques.optionA, optionB=ques.optionB,
                                            optionC=ques.optionC, optionD=ques.optionD,
                                            answer=ques.answer, student=student)
            student_question.save()
            stuExam.questions.add(student_question)
            stuExam.save()

        stuExam.completed = 1
        stuExam.save()
        mins = examMain.duration
        secs = 0

        return render(request, 'student/paper/viewpaper.html', {
            'qpaper': qPaper, 'question_list': stuExam.questions.all(), 'student': student, 'exam': paper, 'min': mins, 'sec': secs
        })

    elif request.method == 'POST' and request.POST.get('papertitle', False):
        paper = request.POST['paper']
        title = request.POST['papertitle']
        stuExam = StuExam_DB.objects.get(examname=paper, student=student)
        qPaper = stuExam.qpaper

        examQuestionsList = stuExam.questions.all()
        examScore = 0
        for ques in examQuestionsList:
            ans = request.POST.get(ques.question, False)
            if not ans:
                ans = "E"
            ques.choice = ans
            ques.save()
            if ans == ques.answer:
                examScore = examScore + 1

        stuExam.score = examScore
        stuExam.save()

        return render(request, 'student/result/result.html', {
            'Title': title, 'Score': examScore, 'student': student
        })

    return render(request, 'student/exam/viewexam.html', {
        'student': student, 'paper': studentExamsList
    })

student/views/result.py
from django.shortcuts import render, redirect
from django.http import HttpResponseForbidden
from main.models import *
from django.contrib.auth.models import User
from student.models import *


def results(request):
    student = request.user

    studentGroup = Special_Students.objects.filter(students=student)
    studentExamList = StuExam_DB.objects.filter(student=student, completed=1)

    if request.method == 'POST':
        paper = request.POST['paper']
        viewExam = StuExam_DB.objects.get(examname=paper, student=student)
        return render(request, 'student/result/individualresult.html', {
            'exam': viewExam, 'student': student, 'quesn': viewExam.questions.all()
        })

    return render(request, 'student/result/results.html', {
        'student': student, 'paper': studentExamList
    })

student/templates/student/result/individualresult.html
{% extends 'student/base/base.html' %}

{% block title %}Result{% endblock title %}
{% block nav_title %}{{ exam.examname }}{% endblock nav_title %}
{% block url %}{% url 'student:index' %}{% endblock url %}
{% block action %}Home{% endblock action %}

{% block body %}
    <div class="container-fluid my-2">
        <h3 align="center">Score : {{ exam.score }}</h3>
        <ol class="list-group">
            {% for ques in quesn %}
            <li class="list-group-item list-group-item-action my-1"><h6><i>{{ ques.question }}</i></h6>
               &nbsp; <strong>A.</strong> {{ques.optionA}}<br>
               &nbsp; <strong>B.</strong> {{ques.optionB}}<br>
               &nbsp; <strong>C.</strong> {{ques.optionC}}<br>
               &nbsp; <strong>D.</strong> {{ques.optionD}}<br>
            <hr>

            {% if ques.choice != 'E' %}
            <a>Selected Option - {{ques.choice}}</a><br>
            {% endif %}
            <a>Correct answer - {{ques.answer}}</a><br>
            {% if ques.choice == ques.answer and ques.choice != 'E' %}
            <a>Status: Correct</a><br>
            {% elif ques.choice == 'E' %}
            <a>Status: Not attempted</a><br>
            {% else %}
            <a>Status: Wrong</a><br>
            {% endif %}
            </li>
            {% endfor %}
        </ol>
    </div>
{% endblock body %}

student/templates/student/result/result.html
{% extends 'student/base/base.html' %}

{% block title %}View Paper{% endblock title %}
{% block nav_title %}{{ Title }}{% endblock nav_title %}
{% block url %}{% url 'student:index' %}{% endblock url %}
{% block action %}Home{% endblock action %}

{% block body %}
<br/>
<center>
    <div style="width: 80%;" class="jumbotron container-fluid my-2">
        <h1 class="display-4">Congratulations!🎉</h1>
        <p class="lead">You have successfuly submitted your response.</p>
        <hr class="my-4">
        <p>Visit the link below to check your result.</p>
        <p class="lead">
          <a class="btn btn-primary" href="{%url 'student:results'%}"  role="button">Check results</a>
        </p>
    </div>
</center>
{% endblock body %}

student/templates/student/result/results.html
{% extends 'student/base/base.html' %}

{% block title %}Results{% endblock title %}
{% block nav_title %} Results {% endblock nav_title %}
{% block url %}{% url 'student:index' %}{% endblock url %}
{% block action %}Home{% endblock action %}
{% block body %}

<div style="width: 80%;" class="container-fluid my-2">
        <ul class="list-group">
            {% for i in paper %}
                {% if  i.completed == 1 %}
                <li class="list-group-item list-group-item-action my-1"><h5>{{ i.examname }}</h5>
                    <form method="POST">
                        {% csrf_token %}
                        <input type="hidden" value="{{ i.examname }}" name="paper">
                        <input type="submit" class="btn btn-info" value="View result">
                    </form>
                </li>
                {% endif %}
            {% endfor %}
        </ul>
    </div>
{% endblock body %}